### ISSUE TITLE
Bot gets flagged after sending 15-20messages, is there a way to avoid it?

### ISSUE THREAD

**Issue by 1337cf** [notxVirus/advanced-discord-dmall#1]
Bot Quarantined
Your bot has been flagged by our anti-spam system for abusive behavior. While your bot is quarantined, it is unable to join any more guilds, or send any direct messages to users it has not messaged before. If you believe this to be in error, [click here](https://dis.gd/app-quarantine) and select "Appeal an action taken on an app/bot" as the Report Type to submit an appeal

Its there a way to avoid it? Messaging works its just that it gets flagged.

**Comment by notxVirus** [comment]
Greetings 1337cf,

If you're looking to send direct messages to a large number of Discord users, it's advisable to utilize Discord bots that are at least 6 months old or older. Attempting to employ recently created bots (1-3 months old) may result in your bot being flagged by the Discord API.
